// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
)

const createUsers = `-- name: CreateUsers :one
INSERT INTO users (id, created_at, updated_at, email)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
   $1
)
RETURNING id, created_at, updated_at, email
`

func (q *Queries) CreateUsers(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUsers, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const deleteAllUsers = `-- name: DeleteAllUsers :many
DELETE FROM users 
RETURNING id, created_at, updated_at, email
`

func (q *Queries) DeleteAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, deleteAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
